apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker-service:latest
          imagePullPolicy: IfNotPresent 
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/postgres"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
